HW + additional tasks completed
Pawel-Eliszewski/nodejs-homework-template pull request #2
Opened 2023-08-30 23:32 UTC by Pawel-Eliszewski

HW + additional tasks completed

2023-08-31 00:24 UTC, RadziuMM requested changes
Te validateAsync będzie sypał błędem to catch'a. Zrób sobie to za pomocą validate
``` 
const { error } = userLoginSchema.validate(req.body);
if (error?.message) {
  return res.status(400).send({ error: error.message })
}
```

2023-08-31 00:24 UTC, RadziuMM commented on server/middleware/auth.js
> +    if (!user || err) {
brakuje porównania user.token z tokenem z req. Teraz możesz się wylogować a na stary token /current nadal działa

2023-08-31 00:24 UTC, RadziuMM commented on server/controllers/users.js
> +    const results = await usersService.getOne(id);
req.user === results. Nie ma potrzeby pobierać 2 raz i sprawdzać czy istnieje. Od tego jest middelwere auth

2023-09-01 23:02 UTC, Pawel-Eliszewski commented on server/middleware/auth.js
> +    if (!user || err) {
Zrobiłem coś takiego: 

  const reqToken = req.headers["authorization"].slice(7);
    if (!user || err || user.token !== reqToken)

Ale pewnie da się zrobić lepiej?

2023-09-01 23:02 UTC, Pawel-Eliszewski commented on server/controllers/users.js
> +    const results = await usersService.getOne(id);
Poprawione :)

2023-09-01 23:02 UTC, Pawel-Eliszewski commented
> Te validateAsync będzie sypał błędem to catch'a. Zrób sobie to za pomocą validate
> 
> ```
> const { error } = userLoginSchema.validate(req.body);
> if (error?.message) {
>   return res.status(400).send({ error: error.message })
> }
> ```

Poprawione :)
Oprócz tego powyżej musiałem dodać jeszcze w modelu user w user.methods.validPassword warunek if (password) bo inaczej bcrypt (zamiast Joi) zaczął crashować apke  :D

2023-09-02 00:34 UTC, RadziuMM commented on server/middleware/auth.js
> +    if (!user || err) {
Może być, ja bym zrobił tak:
const token = req.headers.authorization?.split(" ")[1];

2023-09-02 00:35 UTC, RadziuMM approved these changes

2023-09-05 12:39 UTC, closed without merging

2023-09-05 12:41 UTC, Pawel-Eliszewski commented
Everything merged in PR3